### ISSUE TITLE
Un-crouching is incorrectly allowed while under low surfaces

### ISSUE THREAD

**Issue by Birusama** [Sixze/ALS-Refactored#133]
While testing things out, I was able to stand up under low surfaces after crouching under them, causing my head to clip into the ceiling - and then being unable to re-crouch while clipping; this is not ordinarily possible as a default behavior of crouching.

I found that removing the SetStance on line 639 of AlsCharacter.cpp stopped the issue and allowed low surfaces to prevent standing up (until walking out from under them):

```
void AAlsCharacter::UnCrouch(const bool bClientSimulation)
{
	Super::UnCrouch(bClientSimulation);

	// Chance stance instantly without waiting for ACharacter::OnEndCrouch().

	SetStance(AlsStanceTags::Standing);
}
```

However, I'm not sure if removing this negatively impacts anything, as the presence of a comment having this change instantly means it was done intentionally for a purpose.

Full disclosure: I'm super new to the C++ side of things, Github, and ALS and haven't fully looked through all of the code yet to get a full grasp of things.

**Comment by Sixze** [comment]
It was indeed intentional, but I can't remember exactly why 🥲. Anyway, I fixed this in 42daee3183587b244c54870e7024af0568f84318 and everything still looks fine.
