### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by Drewdaddy07** [Sixze/ALS-Refactored#137]
I dont know if I am just a dunce but I cant seem to get this working with a plain UE5 project. I just get a "Project name could not be compiled. Try rebuilding from source manually." I am on Unreal version 5.0.3.

**Comment by Sixze** [comment]
Build it with Visual Studio or Rider to see a list of errors.

**Comment by Drewdaddy07** [comment]
I figured it out, turns out you need to 1. enable both metasound and enhanced input, and 2. follow the read me in the code.
