### ISSUE TITLE
Can still uncrouch under objects

### ISSUE THREAD

**Issue by Drewdaddy07** [Sixze/ALS-Refactored#138]
This is somewhat of a duplicate of #133 but as it was updated I figured Id make another one. The same thing happens for me in the newest version. I am able to uncrouch under objects and clip my head through.

**Comment by Sixze** [comment]
Can't reproduce, please provide more details.

**Comment by Drewdaddy07** [comment]
As far as I know I am using the default plugin. I have advanced sessions and advanced steam sessions as well. It seems the standing stance is still being set while under objects. Thats about all I know

Public code
[Public.zip](https://github.com/Sixze/ALS-Refactored/files/9389604/Public.zip)

Private
[Private.zip](https://github.com/Sixze/ALS-Refactored/files/9389607/Private.zip)

**Comment by Sixze** [comment]
You are not using the latest plugin version.

**Comment by Drewdaddy07** [comment]
Sorry for asking for so much but as far I as know this is still an issue. Just downloaded a new release and installed it into my plugin folder. I am still able to uncrouch under objects. I still have the advanced sessions plugins.
