### ISSUE TITLE
Tapping crouch twice while under an obstacle requires tapping twice to crouch after standing

### ISSUE THREAD

**Issue by Birusama** [Sixze/ALS-Refactored#141]
If un-crouching while under a low obstacle, it now correctly remains crouched (recent fix #133) and correctly stands up after leaving out from under the low obstacle. (Desired stance to standing?)

However, if you tap crouch twice while under the obstacle, it is expected to remain crouched when exiting out from under the low obstacle (desired stance back to crouch?) but it instead stands up. (Desired stance still standing?) Strangely, it then requires two more taps of crouch in order to go back to actually crouching; making it behave as though the system sees your stance as already crouching as would have been correct.

**Comment by Sixze** [comment]
Fixed in f0e53e41f133bbaab2874ceafbcf8e2c2e72f2e0.
