### ISSUE TITLE
Compiling as a plugin for team distribution.

### ISSUE THREAD

**Issue by CanisHelix** [Sixze/ALS-Refactored#144]
When compiling as plugin via RunUAT to distribute to a team, multiple errors are raised in the form of:

Example:
```
Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
```

Complete List(Too long for git) : https://pastebin.com/AaRGwPzn

This was fixed in Community back in https://github.com/dyanikoglu/ALS-Community/pull/169, I can do the same here with the same Category names if you wish, or if you'd like to use different names that's okay too. But it's a big list.

**Comment by Sixze** [comment]
Fixed in d253a4ed26b933c68ebda2822b7e8345115d8a3a.
