### ISSUE TITLE
Bug? trying to walk using walk backwards "S" holding to go sideways

### ISSUE THREAD

**Issue by lucastoledo95** [Sixze/ALS-Refactored#152]
When trying to walk using walk backwards "S" holding and pressing "A" and "D" to go sideways is not going.

**Comment by lucastoledo95** [comment]
when holding "Alt" it gets stuck and even stops walking, but just clicking once it works perfect, in the test I'm trying to use it as if it were the same as the "SHIFT" being held.
This is how i thought it was working

**Comment by Sixze** [comment]
You are probably just triggering an editor action by pressing `Alt+S`, idk.

![image](https://user-images.githubusercontent.com/16257871/189454632-9319b7db-2c65-42e9-9a50-1f0c334a1a72.png)

**Comment by lucastoledo95** [comment]
so ok, thank you
