### ISSUE TITLE
AnimationInstanceSetting: A_Als_Crouch_Turn_90_Left.A_Als_Crouch_Turn_90_Left' needs to be -90 instead of 90

### ISSUE THREAD

**Issue by deadstar619** [Sixze/ALS-Refactored#174]
Hi, I just wanted to say amazing job ! I've noticed you can't enter negative values in the asset itself (AnimationInstanceSetting) and A_Als_Crouch_Turn_90_Left.A_Als_Crouch_Turn_90_Left' needs to be -90 instead of 90. 
cheers!

**Comment by Sixze** [comment]
In fact, the opposite :), there should not be negative numbers in those settings, so I changed -90 to 90.

**Comment by deadstar619** [comment]
Makes sense :) Thanks for the fix and clarification 👍
