### ISSUE TITLE
Always crash on exiting Play

### ISSUE THREAD

**Issue by fakedownboys** [Sixze/ALS-Refactored#176]
If you set Play as Listen Server or Play as Client it will crash on closing Play window.
If you play with Standalone mode Unreal doesnt crashes.

```
Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000038

UnrealEditor_ALSExtras!AAlsCharacterExample::NotifyControllerChanged() [E:\Games\Epic Games\ALSRefactored\ALSRefactored\Plugins\ALSRefactored\Source\ALSExtras\Private\AlsCharacterExample.cpp:23]
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
kernel32
ntdll
```

**Comment by Sixze** [comment]
Update the plugin to the latest commit and try to reproduce the issue again.

**Comment by fakedownboys** [comment]
> Update the plugin to the latest commit and try to reproduce the issue again.

hello, if i get you right, im using currently the latest version of ALS Refactored, so its 4.10

**Comment by fakedownboys** [comment]
> Update the plugin to the latest commit and try to reproduce the issue again.

uh nvm i think i've found what are u talking about, didnt used Github desktop to clone your project, but we will see now

**Comment by fakedownboys** [comment]
> Update the plugin to the latest commit and try to reproduce the issue again.

still crashing but now with this:
`Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000038

UnrealEditor_ALSExtras
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
kernel32
ntdll`

**Comment by fakedownboys** [comment]
For some reason i had in my .sln in AlsCharacterExample.cpp
```
                NewPlayer->InputYawScale_DEPRECATED = 1.0f;
		NewPlayer->InputPitchScale_DEPRECATED = 1.0f;
		NewPlayer->InputRollScale_DEPRECATED = 1.0f;
```
but your AlsCharacterExample.cpp had only
```
		NewPlayer->InputPitchScale_DEPRECATED = 1.0f;
		NewPlayer->InputRollScale_DEPRECATED = 1.0f;
```
so i removed that "NewPlayer->InputYawScale_DEPRECATED = 1.0f;" > builded it again and it doesnt crashes now.
