### ISSUE TITLE
Roll not moving

### ISSUE THREAD

**Issue by Amegaku** [Sixze/ALS-Refactored#182]
Roll animations is playing but character rolling in plase, not move forward. Root motions in enabled

**Comment by Sixze** [comment]
Could you please provide more details? Screenshots, videos, what modifications did you make to the plugin?

**Comment by Amegaku** [comment]
it was not the correct retargeting of animations. 
fix "https://www.youtube.com/watch?v=cVKgCgcRO5k&t=1s"

**Comment by Sixze** [comment]
Closing because this issue is not directly related to ALS. Please ask questions about retargeting in the discussions.
