### ISSUE TITLE
Mantle

### ISSUE THREAD

**Issue by Amegaku** [Sixze/ALS-Refactored#188]
Mantle system work is not correct. Not replication Low_Mantle montage. sometimes outro mantle the controller breaks down altogether and the character does not turn

**Comment by Sixze** [comment]
Could you please provide more details? Screenshots, videos, what modifications did you make to the plugin?

**Comment by Amegaku** [comment]
o. I only added metahuman character

**Comment by Sixze** [comment]
Closing because this issue is not directly related to ALS. Please ask questions about retargeting in the discussions.
