### ISSUE TITLE
Camera can go through wall

### ISSUE THREAD

**Issue by AlexanderGuncenko** [Sixze/ALS-Refactored#2]
hey Sixze,
thank you for the great refactor of ALS 👍 

I noticed a small issue while testing.
the camera can sometimes go through the wall.
![ALS](https://user-images.githubusercontent.com/39985818/128359379-4b1acf69-af39-4719-8c36-df2fd070cbf7.gif)

**Comment by Sixze** [comment]
Hey! Yes, there is such an issue, I will fix it very soon.

**Comment by Sixze** [comment]
Fixed in eee305859877d548497b27cefe4a7e848030ef88.
