### ISSUE TITLE
4.27 - (ALSR 4.8) Host Actor not Replicating Turning

### ISSUE THREAD

**Issue by Merkatroid1** [Sixze/ALS-Refactored#213]
Hey Sixze,

Tried everything for this one - been about 6 hours now.
Please find the video and code below.
Default Pawn Class = None

Essentially, game starts with two players - one client and one host
When everyone is connected, the Gamestate gets the location of the player start.
Gamestate then spawns a character for each player controller to possess.

The host can see the client turn fine, the client cannot see the host turn.
Everything else is replicated fine - overlays etc.
Encountered this in your travels?

https://imgur.com/a/dXbPLMN
https://streamable.com/nqo1a3
Client is on the left, Host on the right.

**Comment by Sixze** [comment]
Sorry, but older versions of the plugin are no longer supported. Try using the latest version for UE 5.0, it has reworked rotation logic.

**Comment by Merkatroid1** [comment]
No worries Sixze - thanks for taking a look.
