### ISSUE TITLE
Character won't mantle when inside a collision sphere

### ISSUE THREAD

**Issue by woodencase01** [Sixze/ALS-Refactored#228]
I'm currently trying to mantle over a simple rock. If the character isn't within a collision sphere, the mantling works. However, if it is within the sphere collision, it's not mantling.

Here is a screenshot of whatMs happening.

![image](https://user-images.githubusercontent.com/4787041/214205921-476fbae5-51e5-4096-95ec-cb021e4680d9.png)

Here is my sphere collision setting:
![image](https://user-images.githubusercontent.com/4787041/214206076-1d93b0a4-4f81-412f-a18b-2977b84be128.png)

**Comment by woodencase01** [comment]
I've made some progress. It seems like the Object Type must **not** be either:
- WorldStatic
- WorldDynamic
- Destructible

The others will work.

I'm not sure if it's normal, it's the first time I have to tweak these. Is it a bug?

**Comment by Ivann97** [comment]
Not a bug, because you can tweak it

Settings->Mantling.MantlingTraceObjectTypes

![image](https://user-images.githubusercontent.com/56310194/216310398-42d06545-569a-42bb-a289-5497e6c96b44.png)

**Comment by woodencase01** [comment]
Thanks for pointing that out! I'll need to dive deeper into these settings. You guys really thought about everything!
