### ISSUE TITLE
Actor rotation is desynced when playing montage with rootmotion which changes rotation

### ISSUE THREAD

**Issue by ameaninglessname** [Sixze/ALS-Refactored#256]
because it's intentionally ignored in `AAlsCharacter::OnRep_ReplicatedBasedMovement`

**Comment by Sixze** [comment]
Does this only happen on simulated proxies?

`ACharacter::OnRep_ReplicatedBasedMovement()` should not affect root motion since it is handled separately in `ACharacter::OnRep_RootMotion()`.

**Comment by Sixze** [comment]
> I found the cause:
> 
> https://github.com/Sixze/ALS-Refactored/blob/bfe487e706c4b7e0959f77cf2bbcaa42dbab6055/Source/ALS/Private/AlsCharacter.cpp#L169-L174

It's disabled because the root motion is replicated from the server, and the roll still works fine, even though it uses root motion too.

**Comment by Sixze** [comment]
Fixed in 8ba31f6080a375a207ee12f044688b928a4683e0.
