### ISSUE TITLE
ue 5.2 support

### ISSUE THREAD

**Issue by murataka** [Sixze/ALS-Refactored#257]
The current version does not compile for linux(server) target, also , some deprecated code prevents compiling in ue 5.2+ . Even fixing it to compile for linux target ue5.1 would still not compile on ue5.2+ versions.

**Comment by murataka** [comment]
* fresh test project with no content.
* compiled using v20_clang-13.0.1-centos7 cross compile toolchain
* ue 5.1 release branch


[testcompile.log](https://github.com/Sixze/ALS-Refactored/files/10969342/testcompile.log)

**Comment by Xerronn** [comment]
Can also confirm the build failure for Linux. Seems related to the use of the __FUNCTION__ macro

**Comment by murataka** [comment]
The actual reason must be about the toolchain version allowed, as it compiles for windows client.
Testing on a linux platform directly would be a good idea before starting fixing.

**Comment by Sixze** [comment]
It looks like Clang replaces `__FUNCTION__` with a static variable, but MSVC replaces it with a normal string literal, so string literal concatenation doesn't work with `__FUNCTION__` in Clang.

**Comment by Sixze** [comment]
Fixed in feafb8b185378f477736395f39b8c8fd52f3dcfb.

**Comment by murataka** [comment]
Unreal 5.2 preview 1 has just been released. Maybe we can reopen this issue, or create a new one ? 
The error prevents project to open> 

Error		RIGVM_METHOD FAlsRigUnit_CalculatePoleVector::Execute has 1 parameters. Since 5.2 parameters are no longer allowed for RIGVM_METHOD functions.	testcompile	D:\ueprojects\testcompile\Plugins\ALS-Refactored-main\Source\ALS\Public\Nodes\AlsRigUnits.h	66	

![Screenshot 2023-03-23 200538](https://user-images.githubusercontent.com/5358438/227390939-3eb9ca04-d887-4979-84c1-51d75d5f8d85.png)
