### ISSUE TITLE
Camera collides with low mesh

### ISSUE THREAD

**Issue by murataka** [Sixze/ALS-Refactored#263]
Camera jumping while moving on to not so high mesh.

https://user-images.githubusercontent.com/5358438/226060976-ce5558a2-cea8-4d27-8553-c20e7491aefb.mp4

**Comment by Sixze** [comment]
It looks like an issue with camera sockets on your character skeleton. Check that the skeleton has camera sockets and that they are specified in `CS_Als_Default`.
