### ISSUE TITLE
Broken packaging

### ISSUE THREAD

**Issue by Asterix-Us** [Sixze/ALS-Refactored#275]
Whenever I try to package the project, I get this error: 
![image](https://user-images.githubusercontent.com/56967503/230548449-fd6feb45-12be-43e5-bf51-90610076c408.png)
Where PNVEditor would be the same as ALSEditor, and in the uproject is set the same. Any idea why this happens?

**Comment by Sixze** [comment]
![image](https://user-images.githubusercontent.com/16257871/230584423-ce840e00-17b4-4cff-a1fc-9e76df236092.png)

The plugin packs fine, it's probably an issue on your end.

**Comment by Asterix-Us** [comment]
Oh then it's definitely weird... I didn't modify anything in the Editor module tbh, so I'm - pretty much in the dark about what can cause this issue :(
