### ISSUE TITLE
Strange issue with disappearing nodes in AB_Als_Ragdolling and AB_Als_Layering 

### ISSUE THREAD

**Issue by oivio** [Sixze/ALS-Refactored#290]
I did come across strange issue. Just trying integrate this amazing system with GASDocumentation. 
![image](https://user-images.githubusercontent.com/38628851/233021963-ae003e92-b830-4171-a54b-13e221684a1f.png)
and even if I do reconnect everything, place in place as it should be. Compile and save it everything works fine till I do restart. Because then it do again just gone. 

Can someone did come a cross issue like this? I did try to search in logs but did not find anything related to missing (disappearing)  Curve Blend or other Blends.

I am using latest ALS-Refactored without any modifications.

**Comment by Birusama** [comment]
I've unfortunately experienced this issue, but not for those anim BPs specifically.

I had finally resolved it after troubleshooting for a lot more time than I'd like to admit and thinking I had corrupted my project, starting new projects several times until running into it again, and finally learning about Loading Phases before losing the last dregs of my sanity.

Editing ALS.uplugin and changing the Loading Phase of ALSEditor from "PostEngineInit" to anything earlier like "PostDefault" or "Default" should resolve this issue for you; if it does not, then perhaps one of the other modules, but it seemed specific to ALSEditor.

**Comment by oivio** [comment]
Big thanks @Birusama for the hint. That issue is chasing me since yesterday and in get me in to insanity but, somehow I feel your clue is the right direction.

**Comment by Sixze** [comment]
Should be fixed in 07695fc1237cad3586d81ed4e5f294c5d5f52cf7.
I've never encountered this issue myself, so I can't say if it's actually fixed or not.
