### ISSUE TITLE
the camera sinks in the floor, when ragdoll 

### ISSUE THREAD

**Issue by AlexanderGuncenko** [Sixze/ALS-Refactored#3]
![ALS](https://user-images.githubusercontent.com/39985818/128394530-8e782f15-e58d-46ce-a82c-9aab31f84d28.gif)

**Comment by AlexanderGuncenko** [comment]
and while roll
![ALS](https://user-images.githubusercontent.com/39985818/128395237-cffb8fe9-b296-4df2-a0ab-48a0b6a9a35f.gif)

**Comment by Sixze** [comment]
Fixed in 7bb147b1007a35bd798bba271763d55fd2355edc. Fix is not perfect and there will be more improvements in the future.
