### ISSUE TITLE
Mantle animations/custom animations with curves don't work correctly on packaged builds using UE5.2

### ISSUE THREAD

**Issue by kardmode** [Sixze/ALS-Refactored#314]
When testing a packaged build, curves on animations seem to be ignored. The animations work correctly in editor.
Tested with mantle animations while using a held item overlay as well as custom animations using the curves slot.
Tested on a new project with UE5.2. 
Tested on a packaged build with UE5.1 with no errors.

https://github.com/Sixze/ALS-Refactored/assets/8419064/d91c509e-03bd-49c8-9dbb-c05cda2373c3

**Comment by Sixze** [comment]
Looks like a UE 5.2 bug. ALS Community has this issue too, so I think we should wait for a fix from Epic.

**Comment by ameaninglessname** [comment]
Fixed in [UE-187485](https://forums.unrealengine.com/t/5-2-1-hotfix-released/1206307)
