### ISSUE TITLE
Strange issue with ragdoll and impulses

### ISSUE THREAD

**Issue by woodencase01** [Sixze/ALS-Refactored#317]
I've been playing with ragdolls and it seems to behave very differently than what I had with the blueprint version of ALS.

On fire, I'm simply applying an impulse on the bone according to the direction of the bullet:
![image](https://github.com/Sixze/ALS-Refactored/assets/4787041/d2668c41-83cc-45c4-8fb2-1f2b99e05819)

And I get the following result:

https://github.com/Sixze/ALS-Refactored/assets/4787041/3c3f5380-7eef-46c6-901e-552b01c22fab

The impact is very similar for each shot and doesn't feel right.

For comparison, here is the same code using ALS 4.0:

https://github.com/Sixze/ALS-Refactored/assets/4787041/6ec9353a-950e-4d24-9a20-970996d05027

If I get into "AAlsCharacter::StartRagdollingImplementation()" and comment out these lines:

```
static constexpr auto MinSpeedLimit{ 200.0f };

	RagdollingState.SpeedLimitFrameTimeRemaining = 8;
	RagdollingState.SpeedLimit = FMath::Max(LocomotionState.Velocity.Size(), MinSpeedLimit);

	GetMesh()->ForEachBodyBelow(UAlsConstants::PelvisBoneName(), true, false, [SpeedLimit = RagdollingState.SpeedLimit](FBodyInstance* Body)
	{
		Body->SetLinearVelocity(Body->GetUnrealWorldVelocity().GetClampedToMaxSize(SpeedLimit), false);
	});
```

Then I get a much better result:

https://github.com/Sixze/ALS-Refactored/assets/4787041/e0f1a8bb-8907-45c1-b8ba-00a5c5fc3a43

**Comment by Sixze** [comment]
It is closely related to this issue: https://github.com/Sixze/ALS-Refactored/issues/60#issuecomment-1153129739

I made the ragdoll initial speed limit hack optional and disabled it (22220fa4dc7c5850e47de35f520a7267477174fe), so the ragdoll should now behave in a more expected way.
