### ISSUE TITLE
Compile error ue5-main

### ISSUE THREAD

**Issue by k-s-s** [Sixze/ALS-Refactored#32]
Hi

I just tried to add this to my project which is ue5-main branch.
I cannot compile and not sure what local fix could be.

Attached the error sample.

Let me know if I am doing something wrong.

Thanks
[als-error.txt](https://github.com/Sixze/ALS-Refactored/files/7360693/als-error.txt)

**Comment by Sixze** [comment]
Sorry, at the moment I only support 5.0 EA, support for full engine version will be added at least after 5.0 Release Candidate.

It looks like there are major API changes related to Large World Coordinates, so I will keep this issue open until the full release of Unreal Engine 5.

**Comment by cosmicmonkeysounds** [comment]
Not sure if this is related, but I'm trying to use this plugin with 5.0EA on Big Sur (Intel), and I keep getting the following error.
I know it says Mac is not in support at the moment, but if anyone has any idea of where I can start to fix this, I'd very much appreciate it. Thanks!

```

Showing Recent Issues
Setting up bundled DotNet SDK


Processing build for Target=Loco2Editor Platform=Mac Configuration=Development -architecture=x86_64 /Users/jpjanigan-mills/Documents/Unreal Projects/Loco2/Loco2.uproject 


Mac using Manual SDK 12.5.1


Creating makefile for ShaderCompileWorker (no existing makefile)


ERROR: Couldn't find target rules file for target 'ShaderCompileWorker' in rules assembly 'UE5Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.


       Location: /Users/Shared/Epic Games/UE_5.0EA/Engine/Intermediate/Build/BuildRules/UE5Rules.dll


       Target rules found:


Running Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool Loco2Editor Mac Development /Users/jpjanigan-mills/Documents/Unreal Projects/Loco2/Loco2.uproject -architecture=x86_64


Mac using Manual SDK 12.5.1


Building Loco2Editor...


[Adaptive Build] Excluded from Loco2 unity file: Loco2GameModeBase.cpp, Loco2.cpp


Performing 2 actions (8 in parallel)


[1/2] Link UnrealEditor-ALSEditor.dylib


Undefined symbols for architecture x86_64:


  "vtable for FAnimNode_BlendListBase", referenced from:


      FAnimNode_BlendListBase::~FAnimNode_BlendListBase() in Module.ALSEditor.cpp.o


  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.


ld: symbol(s) not found for architecture x86_64


clang: error: linker command failed with exit code 1 (use -v to see invocation)


Command /Users/Shared/Epic Games/UE_5.0EA/Engine/Build/BatchFiles/Mac/XcodeBuild.sh failed with exit code 6

```

**Comment by Sixze** [comment]
> Not sure if this is related, but I'm trying to use this plugin with 5.0EA on Big Sur (Intel), and I keep getting the following error. I know it says Mac is not in support at the moment, but if anyone has any idea of where I can start to fix this, I'd very much appreciate it. Thanks!
> 
> Oh, and the project opens up just fine when I remove the plugin, so it's not an issue with that!

Unfortunately, I don't have macOS or Linux to test compilation, so I mostly rely on other people's help with these issues.

**Comment by mbwilding** [comment]
Having the same issue on Linux (Source build of main branch [4.27])

**Comment by mbwilding** [comment]
> Not sure if this is related, but I'm trying to use this plugin with 5.0EA on Big Sur (Intel), and I keep getting the following error. I know it says Mac is not in support at the moment, but if anyone has any idea of where I can start to fix this, I'd very much appreciate it. Thanks!
> 
> Oh, and the project opens up just fine when I remove the plugin, so it's not an issue with that!
> 
> ```
> 
> Showing Recent Issues
> Setting up bundled DotNet SDK
> 
> 
> Processing build for Target=Loco2Editor Platform=Mac Configuration=Development -architecture=x86_64 /Users/jpjanigan-mills/Documents/Unreal Projects/Loco2/Loco2.uproject 
> 
> 
> Mac using Manual SDK 12.5.1
> 
> 
> Creating makefile for ShaderCompileWorker (no existing makefile)
> 
> 
> ERROR: Couldn't find target rules file for target 'ShaderCompileWorker' in rules assembly 'UE5Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
> 
> 
>        Location: /Users/Shared/Epic Games/UE_5.0EA/Engine/Intermediate/Build/BuildRules/UE5Rules.dll
> 
> 
>        Target rules found:
> 
> 
> Running Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool Loco2Editor Mac Development /Users/jpjanigan-mills/Documents/Unreal Projects/Loco2/Loco2.uproject -architecture=x86_64
> 
> 
> Mac using Manual SDK 12.5.1
> 
> 
> Building Loco2Editor...
> 
> 
> [Adaptive Build] Excluded from Loco2 unity file: Loco2GameModeBase.cpp, Loco2.cpp
> 
> 
> Performing 2 actions (8 in parallel)
> 
> 
> [1/2] Link UnrealEditor-ALSEditor.dylib
> 
> 
> Undefined symbols for architecture x86_64:
> 
> 
>   "vtable for FAnimNode_BlendListBase", referenced from:
> 
> 
>       FAnimNode_BlendListBase::~FAnimNode_BlendListBase() in Module.ALSEditor.cpp.o
> 
> 
>   NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
> 
> 
> ld: symbol(s) not found for architecture x86_64
> 
> 
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> 
> Command /Users/Shared/Epic Games/UE_5.0EA/Engine/Build/BatchFiles/Mac/XcodeBuild.sh failed with exit code 6
> ```

Having the same issue on Linux (Source build of main branch [4.27])
Trying to sort it now and will fork/pull request.

`
ld.lld: error: undefined symbol: vtable for FAnimNode_BlendListBase
>>> referenced by AnimNode_BlendListBase.h:24 (Runtime/AnimGraphRuntime/Public/AnimNodes/AnimNode_BlendListBase.h:24)
>>>               /Path/ProjectName/Plugins/ALS-Refactored/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/ALSEditor/Module.ALSEditor.cpp.o:(FAnimNode_BlendListBase::~FAnimNode_BlendListBase())
>>> the vtable symbol may be undefined because the class is missing its key function (see https://lld.llvm.org/missingkeyfunction)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by Brizztech** [comment]
Hi @mhomde

Would like to connect with you to discuss a career opportunity.

**Comment by Benbentwo** [comment]
@Sixze Running into this with `main` branch of this, I see this is closed did you happen to find a fix. 

I did branch off main but do have customizations.

**Comment by Benbentwo** [comment]
Turns out ALSEditor, this module, needed `"AnimGraphRuntime",` added to its `PrivateDependencyModuleNames` which is where the base class lives. 

Happy to open a PR to clarify, but not sure if its a one off issue for my machine.

**Comment by CanisHelix** [comment]
I'm encountering the same problem with a LinuxClient compilation too. Probably need to get a PR in to fix this.
