### ISSUE TITLE
Mantle / Vault on actor that gets destroyed teleports the actor

### ISSUE THREAD

**Issue by xkamronx** [Sixze/ALS-Refactored#331]
If you mantle / vault on to an Actor that is destroyed during the vault, the player teleports to world origin instead of falling down to the ground.

**Comment by xkamronx** [comment]
Any updates planned?

**Comment by Sixze** [comment]
Currently busy with work/personal project, so no ETA.

**Comment by Sixze** [comment]
Fixed in 966308e79d6e8505c9437302d1cbfb594c99e5b7.

**Comment by xkamronx** [comment]
Thank you for the fixes!
