### ISSUE TITLE
The TryCalculatePoleVector not work well if the three point collinear

### ISSUE THREAD

**Issue by watsonsong** [Sixze/ALS-Refactored#340]
The [TryCalculatePoleVector](https://github.com/Sixze/ALS-Refactored/blob/main/Source/ALS/Private/Nodes/AlsRigUnits.cpp#L24C13-L24C35) may not work correct if the ItemA, ItemB and ItemC is collinear.

`BLocation - ProjectionLocation` may very small, less than 1cm the direction will be incorrect. May be there need fallback for this case, for example use the ItemA forward vector?

**Comment by Sixze** [comment]
Fixed in 95e87349b39da8af05bfc338d73967240d4e0cb4.

The last successful result will be reused if a new pole vector can't be calculated.
