### ISSUE TITLE
Rotating too fast in one direction causes rotation in the other direction

### ISSUE THREAD

**Issue by kriNon** [Sixze/ALS-Refactored#345]
When spinning the character around (rotating quickly on the spot), the character will always try its best to keep up with the joystick input direction. If you spin the joystick too fast for the character to be able to keep up with, the character eventually falls out of sync enough with the input direction that it becomes a shorter path to rotate in the opposite direction (to reach the intended direction).

In this case, preserving rotation direction seems more important than taking the shortest route.

Edit: I'm working on a PR that addresses this issue.

**Comment by Sixze** [comment]
I'm not sure if this is really worth fixing, as this situation doesn't usually occur during gameplay and isn't very noticeable.

It will be great if you can fix it, but if I were you I'd probably start by simply limiting how much the character's rotation can lag behind the stick rotation when the stick rotation speed is very high. Something similar to the already existing logic from `AAlsCharacter::RefreshGroundedNotMovingAimingRotation()` and `UAlsAnimationInstance::RefreshLook()`. But I don't think it will be that simple.
