### ISSUE TITLE
Overlay Mode not Replicated to Clients (From Server)

### ISSUE THREAD

**Issue by RemainingToast** [Sixze/ALS-Refactored#349]
This is an easy fix, however its easier to open an issue than a pr because I would need to cherry-pick the specific change from my fork.

The fix: https://github.com/RedactedStar/ALSv4-Lyra/commit/a6d9697a037020537a9926e69e7bdc2c7952562c
> The `OnLocomotionChanged` delegate is unrelated obviously..

**Comment by Sixze** [comment]
Fixed in 40241e30628ccfc29c1b519421a8421f196ca860.
