### ISSUE TITLE
Node  Clamp 01 2  could not be resolved.

### ISSUE THREAD

**Issue by coolzilj** [Sixze/ALS-Refactored#368]
CR_AIs can't be compiled due to these errors, seems related to https://github.com/Sixze/ALS-Refactored/commit/1a86cc455a3447c588d6a0309e71042b15b37275

**Comment by Sixze** [comment]
I tested the plugin on a new project and did not encounter this issue. Make sure that all the latest plugin changes from the repository are present in your project.
