### ISSUE TITLE
Footstep sound incorrect sometimes (especially when landing)

### ISSUE THREAD

**Issue by xkamronx** [Sixze/ALS-Refactored#381]
Likely an issue with the trace to get the ground type - very often when jumping especially, the landing sound plays default instead of the correct sound (should be dirt, but plays default for example)

**Comment by Sixze** [comment]
Fixed in 6d9e6007a39495f53f3cbe75786a9c0689c14385.

**Comment by xkamronx** [comment]
Is not spawning the sound and effect at all better than playing the wrong one? I think it would be more jarring than it playing the default sound, and could be somewhat game breaking in anything that is PvP focused (randomly getting a silent jump for example).

Any thoughts on what would be causing this to fail?
