### ISSUE TITLE
Character has wrong camera rotation after posses in client.

### ISSUE THREAD

**Issue by andenstudios** [Sixze/ALS-Refactored#387]
Hi,
In my game I have different pawns that I can posses like vehicles, and soldiers (ALS characters). If I posses one of the vehicle (helicopter) and move around and then unposses it, when I go to posses one of the ALS characters the camera will start with the camera rotation of the previous pawn I controlled and then it will keep having this initial offset all the time. This only happens on the client. 
I attach some pictures.
Helicopter being controlled and then unpossesed pressing a key.
![HungryCreatures - Unreal Editor 22-Oct-23 12_00_01](https://github.com/Sixze/ALS-Refactored/assets/106626934/d28b1f97-511c-45cf-9a11-6f48a32f5dc4)

ALS character being possesed after the helicopter with wrong camera offset.
![HungryCreatures - Unreal Editor 22-Oct-23 12_00_07](https://github.com/Sixze/ALS-Refactored/assets/106626934/9c1d0af5-8ddf-4b4d-a314-cb2cb9baa038)

Some more info. When the game starts another pawn (like a RTS view camera is the one that controls and selects which pawn posses).I discarded that the problem is in any of my pawns, I can posses the vehicles and even other soldiers I had with other BP without any issue.
I am using the latest git commit and UE 5.3.1

**Comment by ameaninglessname** [comment]
Looks like your camera rotation has `roll` value on it, you can check it with `showdebug camera`.

**Comment by Sixze** [comment]
Check that `AController::ControlRotation` has a zero roll. Camera rotation, as well as view rotation, is based on this variable, so if there is a roll, the camera will have a roll as well.

Also make sure you are not using the `APawn::AddControllerRollInput()` function.

And if you want, you can globally remove camera roll by tweaking `ViewRollMin` and `ViewRollMax` in `APlayerCameraManager`.

**Comment by andenstudios** [comment]
> Check that `AController::ControlRotation` has a zero roll. Camera rotation, as well as view rotation, is based on this variable, so if there is a roll, the camera will have a roll as well.
> 
> Also make sure you are not using the `APawn::AddControllerRollInput()` function.
> 
> And if you want, you can globally remove camera roll by tweaking `ViewRollMin` and `ViewRollMax` in `APlayerCameraManager`.

Thanks. the problem was that I was changing the roll of the controller. From the other pawns. I just fixed it reseting the roll to 0 when I unposses them.
