### ISSUE TITLE
Third Person to First Person camera view point offset?

### ISSUE THREAD

**Issue by xkamronx** [Sixze/ALS-Refactored#391]
Would it be possible to fix the view modes so they're both looking at the same position?

If you're in third person and look directly at a point, then swap to first person, it moves where you're looking to the left by a decent amount. This can also be worsened by adjusting the third person camera offset to a large amount.

**Comment by ameaninglessname** [comment]
Basically, you need to implement the `aim lock` functionality, which adjust the camera rotation every tick based on `current camera location` and `aim lock point`(look at rotation)
