### ISSUE TITLE
you can jump while rolling

### ISSUE THREAD

**Issue by AlexanderGuncenko** [Sixze/ALS-Refactored#4]
![ALS](https://user-images.githubusercontent.com/39985818/128606902-3876bea9-e354-44cd-ad5e-b3b2b540bf98.gif)
this issue appears only on a client connected to a dedicated server, not in standalone mode.

**Comment by Sixze** [comment]
Fixed in 5bcd6cf4e666356ebeb31ec32177bceaea00b961.
