### ISSUE TITLE
Exception occurs on AAlsCharacter::RefreshRagdolling(float) AlsCharacter_Actions.cpp:826 when AI get's destroyed during ragdol

### ISSUE THREAD

**Issue by victorhmrod** [Sixze/ALS-Refactored#418]
![image](https://github.com/Sixze/ALS-Refactored/assets/63883887/c6587e8f-3a99-472a-a2cf-057951cbf9c1)

**Comment by Sixze** [comment]
Can't reproduce this. Possibly has been fixed here: https://github.com/Sixze/ALS-Refactored/issues/413.
