### ISSUE TITLE
Build fails in UE5-EA (Unresolved External Symbol)

### ISSUE THREAD

**Issue by kriNon** [Sixze/ALS-Refactored#43]
When attempting to build the latest version of ALS-Refactored (currently d1b90620155dee1798bfb10eb54036bef22959ff) the build fails.

Error message is as follows:
![image](https://user-images.githubusercontent.com/3295424/145165206-6f120e97-3f17-4eb3-aaf6-231ac145a728.png)

I have also attached the build log:
[Build Log](https://pastebin.com/SXZ5Rm6Z)

Can confirm that I am having errors building 190a4beeb7c8db2a76c15828e58302ac51b04ba1 and d1b90620155dee1798bfb10eb54036bef22959ff but older versions are compiling without error.

This issue might be related to #42.

**Comment by Sixze** [comment]
Fixed in 53e4c17b5eef7db3b3989e50b7ba3463c9c7f6fc.
