### ISSUE TITLE
ik_hand_gun does not follow overlay states while moving

### ISSUE THREAD

**Issue by Xerronn** [Sixze/ALS-Refactored#440]
ik_hand_gun snaps to the correct location while standing still and changing overlay states, but is transformed by the base locomotion animations (hand sway) and not the overlay state while moving

**Comment by Sixze** [comment]
You should not use the `ik_hand_gun` bone directly. Use `VB hand_l_to_ik_hand_gun` or `VB hand_r_to_ik_hand_gun` instead. See the `AttachOverlayObject` function in `B_Als_Character` for more details.
