### ISSUE TITLE
5.3 ALSRefactored could not be compiled.

### ISSUE THREAD

**Issue by millionart** [Sixze/ALS-Refactored#459]
> Automation Tool Path: "D:\Epic\Epic Games\UE_5.3\Engine\Build\BatchFiles\RunUAT.bat"
> 
> Running AutomationTool...
> Using bundled DotNet SDK version: 6.0.302
> Starting AutomationTool...
> Parsing command line: BuildPlugin -Plugin=D:\Users\username\Git\ALSRefactored\Plugins\ALS-Refactored\ALS.uplugin -Package=D:\Users\username\Git\ALSRefactored\Plugins\ALS-Refactored\Build -Rocket -TargetPlatforms=Win64
> Initializing script modules...
> Total script module initialization time: 0.19 s.
> Executing commands...
> Copying 913 file(s) using max 64 thread(s)
> Reading plugin from D:\Users\username\Git\ALSRefactored\Plugins\ALS-Refactored\Build\HostProject\Plugins\ALS\ALS.uplugin...
> Building plugin for host platforms: Win64
> Running: D:\Epic\Epic Games\UE_5.3\Engine\Binaries\ThirdParty\DotNet\6.0.302\windows\dotnet.exe "D:\Epic\Epic Games\UE_5.3\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" UnrealEditor Win64 Development -Project="D:\Users\username\Git\ALSRefactored\Plugins\ALS-Refactored\Build\HostProject\HostProject.uproject" -plugin="D:\Users\username\Git\ALSRefactored\Plugins\ALS-Refactored\Build\HostProject\Plugins\ALS\ALS.uplugin" -noubtmakefiles -manifest="D:\Users\username\Git\ALSRefactored\Plugins\ALS-Refactored\Build\HostProject\Saved\Manifest-UnrealEditor-Win64-Development.xml" -nohotreload -log="C:\Users\username\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+Epic+Epic+Games+UE_5.3\UBT-UnrealEditor-Win64-Development.txt"
> Log file: C:\Users\username\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+Epic+Epic+Games+UE_5.3\UBT-UnrealEditor-Win64-Development.txt
> HostProject.uproject is has no code, but is being treated as a code-based project because: PythonScriptPlugin plugin is disabled. Creating temporary .Target.cs files.
> Parsing headers for UnrealEditor
>   Running Internal UnrealHeaderTool D:\Users\username\Git\ALSRefactored\Plugins\ALS-Refactored\Build\HostProject\HostProject.uproject D:\Users\username\Git\ALSRefactored\Plugins\ALS-Refactored\Build\HostProject\Intermediate\Build\Win64\UnrealEditor\Development\UnrealEditor.uhtmanifest -WarningsAsErrors -installed
> Total of 142 written
> Reflection code generated for UnrealEditor in 1.1749218 seconds
> Writing manifest to D:\Users\username\Git\ALSRefactored\Plugins\ALS-Refactored\Build\HostProject\Saved\Manifest-UnrealEditor-Win64-Development.xml
> Building UnrealEditor...
> Using Visual Studio 2022 14.39.33521 toolchain (C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519) and Windows 10.0.22621.0 SDK (C:\Program Files (x86)\Windows Kits\10).
> Determining max actions to execute in parallel (12 physical cores, 24 logical cores)
>   Executing up to 12 processes, one per physical core
>   Requested 1.5 GB memory per action, 7.02 GB available: limiting max parallel actions to 4
> ------ Building 20 action(s) started ------
> [1/20] Resource Default.rc2
> [2/20] Resource Default.rc2
> [3/20] Resource Default.rc2
> [4/20] Resource Default.rc2
> [5/20] Compile [x64] SharedPCH.UnrealEd.Cpp20.cpp
> D:\Epic\Epic Games\UE_5.3\Engine\Source\predefined C++ types (compiler internal)(420): error C2248: “FHazardPointerCollection::FHazardRecord::FHazardRecord”: 无法访问 private 成员(在“FHazardPointerCollection::FHazardRecord”类中声明)
> D:\Epic\Epic Games\UE_5.3\Engine\Source\Runtime\Core\Public\Experimental\Containers\HazardPointer.h(86): note: 参见“FHazardPointerCollection::FHazardRecord::FHazardRecord”的声明
> D:\Epic\Epic Games\UE_5.3\Engine\Source\Runtime\Core\Public\Experimental\Containers\HazardPointer.h(77): note: 参见“FHazardPointerCollection::FHazardRecord”的声明
> D:\Epic\Epic Games\UE_5.3\Engine\Source\predefined C++ types (compiler internal)(420): note: 模板实例化上下文(最早的实例化上下文)为
> D:\Epic\Epic Games\UE_5.3\Engine\Source\Runtime\Core\Public\Experimental\Containers\HazardPointer.h(133): note: 查看对正在编译的函数 模板 实例化“void __builtin_array_init_helper<FHazardPointerCollection::FHazardRecord>(_T *,size_t) noexcept(<expr>)”的引用
>         with
>         [
>             _T=FHazardPointerCollection::FHazardRecord
>         ]
> Total time in Parallel executor: 17.01 seconds
> Total execution time: 30.68 seconds
> Took 30.81s to run dotnet.exe, ExitCode=6
> UnrealBuildTool failed. See log for more details. (C:\Users\username\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+Epic+Epic+Games+UE_5.3\UBT-UnrealEditor-Win64-Development.txt)
> AutomationTool executed for 0h 0m 32s
> AutomationTool exiting with ExitCode=6 (6)
> BUILD FAILED
>

**Comment by ameaninglessname** [comment]
It's not related to `ALS-Refactored`, please refer to:
https://forums.unrealengine.com/t/hi-i-keep-having-this-error-while-live-coding-and-i-have-no-idea-what-is-the-issue-here-did-anyone-face-such-a-problem/1425277/18
