### ISSUE TITLE
Remove engine version from .uplugin

### ISSUE THREAD

**Issue by fabriciomsantos** [Sixze/ALS-Refactored#46]
To prevent this popup from appearing in 4.27 and 5.0

![Captura de tela 2021-12-10 170258](https://user-images.githubusercontent.com/37518637/145634593-8afd9223-2daf-488c-942d-596a1de6bd5e.png)

**Comment by Sixze** [comment]
There is a note in README.md:
> Important! If you are using Unreal Engine 4.27 or 5.0 EA, open the `ALS.uplugin` file in any text editor and remove line with `EngineVersion`.

**Comment by fabriciomsantos** [comment]
I saw, I just don't see a reason to have this inside the .uplugin  if the plugin works in multiple version of the engine.

I think if there is something that only works in some versions of the engine, the best approach would be using a `#if`

**Comment by Sixze** [comment]
I want to prevent people from using plugin on older versions of the engine, but yes, this popup is annoying, so I'll think about it.

**Comment by Sixze** [comment]
Fixed in 65e2660560cfbf83f1dd33656d8e7fcdfce3a5f8.
