### ISSUE TITLE
Changes to GetViewInfo in commit 6776ca2 require usage refactor

### ISSUE THREAD

**Issue by EnricoPietrocola** [Sixze/ALS-Refactored#473]
Commit `6776ca2 - Expose UAlsCameraComponent to blueprints` changes how GetViewInfo is used. 
I'm fine in refactoring where I call this function in my code in order to update to this, but I wonder if this is some sort of mistake and it might eventually be reverted?

**Comment by koniferus** [comment]
Thinking this is not intentional as B_ALSXT_PlayerCameraManager and B_ALSXT_Character are now broken on a fresh install

![image](https://github.com/Sixze/ALS-Refactored/assets/601323/aaa3444f-83a2-492c-b197-1639bac23247)

**Comment by Sixze** [comment]
That was intentional, but I reverted it here: a3b9d96291d577499bd018483f18a24170376644.
