### ISSUE TITLE
Vaulting as fast as possible can result in being stuck until dying / reconnecting

### ISSUE THREAD

**Issue by xkamronx** [Sixze/ALS-Refactored#484]
Set up a 'ladder vault' type scenario where you can vault immediately after completing a vault and spam vault.

Can result in not being able to move pretty easily.

**Comment by Sixze** [comment]
I don't quite understand this issue, and it's probably too project specific, there are no cooldowns or anything like that in the plugin to limit it, and there probably won't be.

**Comment by xkamronx** [comment]
Here's a clip of what I mean. Holding shift and vaulting as fast as possible. Default project.

Not asking for a cooldown or anything - this is definitely a bug.

https://github.com/Sixze/ALS-Refactored/assets/26638814/b7bf8fe6-7520-4b6f-910e-14ebfc8d5783

**Comment by Sixze** [comment]
> Here's a clip of what I mean. Holding shift and vaulting as fast as possible. Default project.

Now I see the issue, thanks.

**Comment by Sixze** [comment]
Fixed in 1233a26fbc655bf6559de5917a1756df42963dd7.
