### ISSUE TITLE
Rolling problem in main branch

### ISSUE THREAD

**Issue by RavenGames** [Sixze/ALS-Refactored#49]
In the main branch version rolling stopped working after a fall from height, in version 4.7 it was still OK, adding a landing event on a character and calling the "try start rolling" function has no effect.

**Comment by Sixze** [comment]
I recently disabled this option and accidentally committed it along with other changes.

![image](https://user-images.githubusercontent.com/16257871/146576487-a98b6c60-cf6d-44a1-ac49-b9d29651cba9.png)

**Comment by RavenGames** [comment]
I enabled this option and it works flawlessly, thanks for the info :-)
