### ISSUE TITLE
Climb Physics Issue

### ISSUE THREAD

**Issue by Jinkel92** [Sixze/ALS-Refactored#493]
There is a bug when trying to climb onto an object with physics, in this case it is a vehicle:
![Vídeo sin título ‐ Hecho con Clipchamp](https://github.com/Sixze/ALS-Refactored/assets/38820100/614a6397-1f93-405b-bf9b-7af4c3d68886)

**Comment by xkamronx** [comment]
To add on to this (since I'm playing around with the same thing - adding vehicles)

The sprinting force also seems wildly different. If I walk in to a physics vehicle, it doesn't move. If I sprint in to it, it goes flying like a beach ball.

**Comment by Sixze** [comment]
I have fixed the issue that was messing up the actor's rotation here: 00d05bdaffe393eb0e3f8f8f7d5ca29f28b6b837, but speaking of physics, while the actor is mantling, his capsule still keeps colliding with the environment and as a result it pushes the car away. To fix this you can, for example, disable the actor's collision with the car and afterwards re-enable it, which you can do in the `OnMantlingStarted` and `OnMantlingEnded` functions.

**Comment by Jinkel92** [comment]
> I have fixed the issue that was messing up the actor's rotation here: [00d05bd](https://github.com/Sixze/ALS-Refactored/commit/00d05bdaffe393eb0e3f8f8f7d5ca29f28b6b837), but speaking of physics, while the actor is mantling, his capsule still keeps colliding with the environment and as a result it pushes the car away. To fix this you can, for example, disable the actor's collision with the car and afterwards re-enable it, which you can do in the `OnMantlingStarted` and `OnMantlingEnded` functions.

Ah!, thanks for hotfix :)
