### ISSUE TITLE
Heavy physics during sprint start

### ISSUE THREAD

**Issue by xkamronx** [Sixze/ALS-Refactored#496]
I have a physics actor (a car) that is set to 1350kg. Player is set to 75kg.

If the player walks in to the car, nothing happens. If the player hits the car running full speed, it's mostly fine.

If the player hits the car during the velocity action from beginning to sprint, the car bounces like a beach ball.

 I have disabled basically all of the 'force scaling based on velocity settings' already in an attempt to fix the issue.

**Comment by xkamronx** [comment]
https://github.com/Sixze/ALS-Refactored/assets/26638814/232a8d63-23d3-4227-894d-0db033b7dc60

**Comment by Sixze** [comment]
Could you remove the code inside the `UAlsCharacterMovementComponent::ApplyPendingPenetrationAdjustment()` function and test this again?

By the way, ALS works on top of the character movement component and is not responsible for such interactions.

**Comment by xkamronx** [comment]
> Could you remove the code inside the `UAlsCharacterMovementComponent::ApplyPendingPenetrationAdjustment()` function and test this again?
> 
> By the way, ALS works on top of the character movement component and isn't really responsible for such interactions.

That appears to have fixed the issue with the sprint start punting the vehicle.

**Comment by Sixze** [comment]
Could you create a smallest reproducible example of this issue and send it to me? Something like " here's a cube with physics enabled, and it flies away when the player touches it".

**Comment by xkamronx** [comment]
> Could you create a smallest reproducible example of this issue and send it to me? Something like "here's a cube with physics enabled, and it flies away when the player touches it".

Yeah for sure, will get it over to you this week.

**Comment by xkamronx** [comment]
Sorry for the delay, will work on this ASAP and get it over to you. It might be specific to Chaos vehicles as well so will test that.

**Comment by xkamronx** [comment]
> Could you create a smallest reproducible example of this issue and send it to me? Something like "here's a cube with physics enabled, and it flies away when the player touches it".

Spent some time trying to repro this without the use of the specific vehicle plugin in question, which is based on the legacy vehicle system (not the new chaos one) and doesn't seem like any issues outside of the plugin, so it's likely that the plugin has done something additional that is causing these issues.

(unless there's been changes to ALS since I last updated my main project - I was trying to repro using the latest version)

I'd consider it closed for now unless I'm able to repro without using another plugin.

Thanks for all you do!

**Comment by Sixze** [comment]
If you are sure it is about the `UCharacterMovementComponent::ApplyPendingPenetrationAdjustment()` function, I can make it optional and disabled by default.

**Comment by xkamronx** [comment]
> If you are sure it is about the `UCharacterMovementComponent::ApplyPendingPenetrationAdjustment()` function, I can make it optional and disabled by default.

Commenting out the code in that function did completely fix the issue in the video, just not positive what else that code might be handling otherwise.

I currently completely disabled player physics collisions with the vehicles for the time being.

**Comment by xkamronx** [comment]
I figured it out. The character mesh needs to be set to full collision rather than query only, then it will punt stuff during sprint start like the video I sent. Working on getting you a full repro. Also testing removing the collision from my project on the mesh to see if it breaks anything.

**Comment by Sixze** [comment]
I added the `bAllowImprovedPenetrationAdjustment` setting to `UAlsCharacterMovementComponent`, so you can disable it to fix this issue.
