### ISSUE TITLE
when you fall after a roll, press jump, force is applied.

### ISSUE THREAD

**Issue by Alex-G** [Sixze/ALS-Refactored#5]
when you fall after a roll, the ragdoll mode is activated, then when you press jump, force is applied.

play as a client,
https://user-images.githubusercontent.com/5215249/128867950-3a36c133-17d0-4db3-86c2-90a8edeeb8b6.mp4

**Comment by Sixze** [comment]
Fixed in 2425cef558cfe065d59956cdcec910f9d54eb30b.
