### ISSUE TITLE
The character's legs go into the object

### ISSUE THREAD

**Issue by RavenGames** [Sixze/ALS-Refactored#50]
The character's legs go into the object, could this be eliminated?
If so, and it would mean a significant drop in performance, you could always add a "bool" checkbox on the player blueprint for those interested.

UE 4.27.2, ALS-main today's

https://streamable.com/3cowev

**Comment by Sixze** [comment]
No. Mantling is designed for climbing up steep walls and is not suitable for such complex geometry. In a real game scenario, climbing on such objects should be prohibited.
