### ISSUE TITLE
Very choppy camera when attached to another actor that is moving (quickly?)

### ISSUE THREAD

**Issue by xkamronx** [Sixze/ALS-Refactored#508]
I have passengers attaching to another player's vehicle. The C++ camera setup is brutal when trying to do this.

Here is a comparison to a default camera setup with a springarm compared to the ALS camera, both of these are recorded as the passenger in the same network conditions:

https://github.com/Sixze/ALS-Refactored/assets/26638814/91ed8de0-8a38-4384-987a-aa7c582a5930

Any ideas would be greatly appreciated to fix this issue. I tried changing around the settings in the camera DA but didn't seem to change anything.

When in first person, it also isn't choppy at all. Just looking for a way to clean this up and make it usable in third person.

**Comment by ameaninglessname** [comment]
Make sure the velocity of your vehicle is smoothing enough.

You can try to disable the camera offset lag, and see if the issue pressie.

**Comment by xkamronx** [comment]
> Make sure the velocity of your vehicle is smoothing enough.
> 
> You can try to disable the camera offset lag, and see if the issue pressie.

I don't believe the issue is really with the vehicle at all; as the default camera (shown in video) doesn't have any chop whatsoever in the exact same scenario. I'll try disabling the lag.

**Comment by xkamronx** [comment]
> > > Make sure the velocity of your vehicle is smoothing enough.
> > > You can try to disable the camera offset lag, and see if the issue pressie.
> > 
> > 
> > I don't believe the issue is really with the vehicle at all; as the default camera (shown in video) doesn't have any chop whatsoever in the exact same scenario. I'll try disabling the lag.
> 
> Or you could enable the lag on the spring arm, just helping digging into the issue.

There's no springarm on the ALS C++ camera but I guess enabling lag on the testing springarm might help diagnose.

**Comment by Sixze** [comment]
I'm not sure if it's the camera's fault because in the video, if you look closely, you can see that relative to the world the camera moves smoothly and it's more of likely the car is lagging. Maybe you could provide some reproduction steps or an example project where I could look at this issue in more detail?

**Comment by xkamronx** [comment]
> I'm not sure if it's the camera's fault because in the video, if you look closely, you can see that relative to the world the camera moves smoothly and it's more of likely the car is lagging. Maybe you could provide some reproduction steps or an example project where I could look at this issue in more detail?

In the video, the left side is the same setup but with the static camera. Not really positive since the car itself doesn't lag when the ALS camera is disabled, will try a few other things.
