### ISSUE TITLE
UE 5.4.1 I can't open my project

### ISSUE THREAD

**Issue by DashaKolts** [Sixze/ALS-Refactored#514]
Hi everyone,

I apologize in advance if this question seems basic, but I'm really struggling and could use some help. I have no experience in coding and mainly work with Blueprints. I followed the initial setup guide for the ALS-Refactored plugin (clone the repository and merge the DefaultEngine.ini and DefaultInput.ini files), but I'm encountering several errors, and my project won't open.

Here are the specific errors I'm seeing:
- 'ALS' is Incompatible" The 'ALS' plugin was designed for build 5.3.0, but I saw a discussion where some users mentioned that the plugin works with version 5.4.
- Missing MyProject Modules: "The following modules are missing or built with a different engine version: ALS, ALSCamera, ALSExtras, ALSEditor. Would you like to rebuild them now?"
- Error: "MyProject could not be compiled. Try rebuilding from source manually."
Is there something I'm missing or doing wrong in the setup?

Thank you for any help!

**Comment by murataka** [comment]
edit the Als.uplugin change EngineVersion to 5.4.1 from 5.3.0

{
	"FileVersion": 3,
	"Version": 14,
	"VersionName": "4.13",
	"FriendlyName": "Advanced Locomotion System Refactored",
	"Description": "Completely reworked and improved С++ version of Advanced Locomotion System V4.",
	"Category": "Animation",
	"CreatedBy": "Sixze",
	"CreatedByURL": "https://github.com/Sixze",
	"DocsURL": "https://github.com/Sixze/ALS-Refactored",
	"MarketplaceURL": "https://www.unrealengine.com/marketplace/en-US/product/advanced-locomotion-system-v1",
	"SupportURL": "https://github.com/Sixze/ALS-Refactored/discussions",
	"EngineVersion": "5.3.0", 
	"EnabledByDefault": true,

**Comment by murataka** [comment]
And use discussions for your questions .

**Comment by DashaKolts** [comment]
> And use discussions for your questions .

Thank you and sorry. I still have a persistent problem and created a discussion about it. Thanks again!

**Comment by DashaKolts** [comment]
> And use discussions for your questions .

Thank you and sorry. I still have a persistent problem and created a discussion about it. Thanks again!
