### ISSUE TITLE
Cannot compile on windows, error with compiling the Camera part.

### ISSUE THREAD

**Issue by rallymoose2** [Sixze/ALS-Refactored#519]
C:\ALS-Refactored-main\Build\HostProject\Plugins\ALS\Source\ALSCamera\Private\AlsCameraComponent.cpp(568): error C2027: use of undefined type 'FOverlapResult'

C:\Program Files\Epic Games\UE_5.4\Engine\Source\Runtime\Engine\Public\WorldCollision.h(26): note: see declaration of 'FOverlapResult'

C:\ALS-Refactored-main\Build\HostProject\Plugins\ALS\Source\ALSCamera\Private\AlsCameraComponent.cpp(569): error C2027: use of undefined type 'FOverlapResult'

C:\Program Files\Epic Games\UE_5.4\Engine\Source\Runtime\Engine\Public\WorldCollision.h(26): note: see declaration of 'FOverlapResult'

C:\ALS-Refactored-main\Build\HostProject\Plugins\ALS\Source\ALSCamera\Private\AlsCameraComponent.cpp(574): error C2027: use of undefined type 'FOverlapResult'

C:\Program Files\Epic Games\UE_5.4\Engine\Source\Runtime\Engine\Public\WorldCollision.h(26): note: see declaration of 'FOverlapResult'

C:\ALS-Refactored-main\Build\HostProject\Plugins\ALS\Source\ALSCamera\Private\AlsCameraComponent.cpp(574): error C2027: use of undefined type 'FOverlapResult'

C:\Program Files\Epic Games\UE_5.4\Engine\Source\Runtime\Engine\Public\WorldCollision.h(26): note: see declaration of 'FOverlapResult'
C:\ALS-Refactored-main\Build\HostProject\Plugins\ALS\Source\ALSCamera\Private\AlsCameraComponent.cpp(574): error C2119: 'OverlapBody': the type for 'const auto *' cannot be deduced from an empty initializer

C:\ALS-Refactored-main\Build\HostProject\Plugins\ALS\Source\ALSCamera\Private\AlsCameraComponent.cpp(576): error C2446: '==': no conversion from 'nullptr' to 'int'

C:\ALS-Refactored-main\Build\HostProject\Plugins\ALS\Source\ALSCamera\Private\AlsCameraComponent.cpp(576): note: A native nullptr can only be converted to bool or, using reinterpret_cast, to an integral type

**Comment by Sixze** [comment]
Fixed after switching to UE 5.4.
