### ISSUE TITLE
UAlsAnimationInstance::RefreshVelocityBlend may produce NaN when velocity is zero?

### ISSUE THREAD

**Issue by watsonsong** [Sixze/ALS-Refactored#524]
When the character is not moving, the RelativeVelocityDirection may get a zero value. Which lead to the TargetVelocityBlend contains NaN. It could be better check this. The NaN may pass to ForwardAmount on some platform. It may lead the animation has some error.

**Comment by Sixze** [comment]
Fixed here: https://github.com/Sixze/ALS-Refactored/pull/525.
