### ISSUE TITLE
Footstep decals occur on top of the character's feet.

### ISSUE THREAD

**Issue by mbwilding** [Sixze/ALS-Refactored#53]
They appear on the ground as you'd expect but they can be seen on the player's feet too.

**Comment by Sixze** [comment]
Yes, this is just Unreal's default behavior.

You can turn off decals using the `bReceivesDecals` parameter in the character's mesh component, but I didn't touch it because this parameter turns off all decals, which can be very confusing, and this is not exactly what ALS is responsible for.
