### ISSUE TITLE
Disconnected function in AB_Als_Standing

### ISSUE THREAD

**Issue by MrWilsonWilson** [Sixze/ALS-Refactored#552]
**Describe the bug**
I think this disconnected function is an oversight

**To reproduce**
Navigate to PlayStopRightTransitionAnimation in AB_Als_Standing

**Expected behavior**
Function should be connected

**Screenshots and videos**
![image](https://github.com/user-attachments/assets/4cdebed2-29d7-4476-a260-1438165c9ba0)

**Additional context**
Great update

**Comment by Sixze** [comment]
Fixed.
