### ISSUE TITLE
Error when load Animation Blueprint in CPP

### ISSUE THREAD

**Issue by wantg** [Sixze/ALS-Refactored#555]
```
class SOMEGMAE_API ACharacter_Base : public AAlsCharacterExample {
    ACharacter_Base();
};

ACharacter_Base::ACharacter_Base(){
    GetMesh()->SetAnimClass(LoadClass<UAnimInstance>(nullptr, TEXT("/Als/ALS/Character/AB_Als.AB_Als_C")));
}
```

Error:
Plugins\ALS-Refactored\Content\ALS\Editor\B_Als_AnimationModifier_FootSyncMarkers.uasset: CreateExport: 
Failed to load Class /Script/AnimationModifierLibrary.FootstepAnimEventsModifier as Parent 
for BlueprintGeneratedClass /ALS/ALS/Editor/B_Als_AnimationModifier_FootSyncMarkers.B_Als_AnimationModifier_FootSyncMarkers_C - both will fail to load

UE 5.4

**Comment by ameaninglessname** [comment]
Please avoid hard coding asset path in code though.

**Comment by wantg** [comment]
I've always thought that filling in the necessary properties in the code so they're not blank would be more friendly to other people, especially people who don't know programming.

**Comment by wantg** [comment]
Thank you for your suggestion

**Comment by ameaninglessname** [comment]
IMO, that's better be done with a blueprint base class instead of in code which is error-prone.
