### ISSUE TITLE
Compile error(warning) happen on linux in AlsAnimationInstance.

### ISSUE THREAD

**Issue by watsonsong** [Sixze/ALS-Refactored#556]
Compile Error happen on linux(treat warning as error):
```
AlsAnimationInstance.cpp:226:22: error: braces around scalar initializer [-Werror,-Wbraced-scalar-init]
    .WalkableFloorAngle{LocomotionState.WalkableFloorAngle},
```

**Comment by watsonsong** [comment]
> .WalkableFloorAngle{LocomotionState.WalkableFloorAngle},
This code is [here](https://github.com/Sixze/ALS-Refactored/blob/a1f05ce4a2aafd5281e05dcb6021fd6cc6f4f6f2/Source/ALS/Private/AlsAnimationInstance.cpp#L218)

**Comment by ameaninglessname** [comment]
Ah, it's me the one who didn't get latest changes.😅

**Comment by Sixze** [comment]
No more relevant after 5fa18e52168befc192c1835e4040e631e6cb9968.
