### ISSUE TITLE
Fatal Error Crash due to MetaSounds after long gameplay

### ISSUE THREAD

**Issue by xkamronx** [Sixze/ALS-Refactored#559]
All of my AI use the same footsteps setup as the player at the moment, so the AI also uses the Footstep notify like the player.

I have attached the error log leading up to the crash. The fatal error is reported as: 
`Assertion failed: FoundElement->NumConsumers.GetValue() >= 1 [File:C:\ue\532\Engine\Source\Runtime\Engine\Private\AudioStreamingCache.cpp] [Line: 949]`

With a ton of repeating errors about the below before crashing:
`[2024.09.29-03.34.42:305][597]LogMetaSound: Error: Node with registry key 'External_None.52A8D16949DCC6F065964FA776C5546F_1.0' already registered by asset '/ALS/ALS/Audio/Footsteps/MS_Als_Footstep.MS_Als_Footstep'. The previously registered node will be overwritten. This can happen if two classes share the same name or if METASOUND_REGISTER_NODE is defined in a public header.`

[Metasound Crash.txt](https://github.com/user-attachments/files/17177752/Metasound.Crash.txt)

**Comment by xkamronx** [comment]
This crash has been happening for at least the last year or so, in basically every version (I haven't updated to 5.4 and don't have the most recent updates since 5.4, but am up to date with 5.3).

It takes a few hours of continuous gameplay for the error to start triggering, but once it does, it just continues to walk until all of the audio starts to delay, stop, then suddenly all of the footsteps hit at the same time like a shotgun, and the game crashes.

**Comment by xkamronx** [comment]
My setup also includes different MS_Als_Footsteps_TYPE that were duplicated from the default one to have different sounds based on the material. I assumed this was correct due to the FES_Als_Settings having a setup that seemed to lean to doing it this way. If that's wrong, maybe having different MetaSound Sources duplicated from the default one is causing the issue.

**Comment by ameaninglessname** [comment]
Have you try [this solution](https://forums.unrealengine.com/t/metasound-error/1211669/2)?

**Comment by xkamronx** [comment]
> Have you try [this solution](https://forums.unrealengine.com/t/metasound-error/1211669/2)?

Not the same issue unfortunately.

**Comment by xkamronx** [comment]
The reason for this crash, I believe, is either using the ALS notifies on a character that isn't the ALS Character, OR...

Duplicating the Meta Sound to create different footstep sounds, but using the same MetaSound Patch for each one.

I removed the ALS notify from the non-ALS AI, and also created new, separate MetaSound Patches for the different material sounds. Appears to be fixed.
