### ISSUE TITLE
Weird effect when getting up from ragdoll

### ISSUE THREAD

**Issue by POWER48** [Sixze/ALS-Refactored#561]
https://github.com/user-attachments/assets/6f5a7066-3b75-40cf-9814-bc0971d823ec

I use Physics Blend weight and Bodies Bellow simulate physics to apply an interaction when getting shooted, i don't know if the issue comes from that

**Comment by ameaninglessname** [comment]
https://github.com/Sixze/ALS-Refactored/discussions/421#discussioncomment-7914376

**Comment by POWER48** [comment]
With the animation rewind Debugger i can't replay the problem, but i found that it occurs only at low framerate (30-60 fps)

**Comment by ameaninglessname** [comment]
> With the animation rewind Debugger i can't replay the problem, but i found that it occurs only at low framerate (30-60 fps)

Could you figure out what exactly changed? Location of the capsule or the mesh. By logging or print those value on screen every frame.

Then you could try to add a data break-point for it to track down the issue.

**Comment by POWER48** [comment]
OK so the capsule doesn't move, it's only the mesh that takes this position and then go back, i will investigate further

**Comment by POWER48** [comment]
Ok so i resolve the issue, the problem was that i called the stop ragdolling in a function with a timer, so maybe it was called a thread problem. Thanks for the help given, it helped me to debug.
