### ISSUE TITLE
Character mesh hovers when a visibility blocking volume is spawned.

### ISSUE THREAD

**Issue by Magic-Summer** [Sixze/ALS-Refactored#580]
In my use case, I toss a flashbang grenade at the enemy character, which is supposed to block it from seeing the player. The enemy then hovers above the ground for a few seconds.
The enemy character should not hover.

AFAIK this happens after the commit from 6 oct 18:34 SHA  [5fa18e5](https://github.com/Sixze/ALS-Refactored/commit/5fa18e52168befc192c1835e4040e631e6cb9968)
This commit changed the character control rig.
The control rig [ALS\Character\CR_Als](https://github.com/Sixze/ALS-Refactored/blob/main/Content/ALS/Character/CR_Als.uasset) contains a function `TraceFootOffset` which calls a function `Foot Offset Trace`. This in turn uses a hardcoded `Trace Channel = Visibility`.
When I change this trace channel value to my custom trace channel, the problem is fixed,

*Suggested Solution*
Promote `Trace Channel` to a variable, allowing it to be easily configurable to project-specific requirements.

**Comment by Magic-Summer** [comment]
![CR_Als](https://github.com/user-attachments/assets/3b87856f-e2ec-4473-bc2d-1bf1d110e288)
Workaround

**Comment by Sixze** [comment]
It is not hardcoded. As you showed, you can change this setting in the asset or create a variable for it :)
