### ISSUE TITLE
Unable to create new BP based on AlsCharacterExample class.

### ISSUE THREAD

**Issue by jamesonjb** [Sixze/ALS-Refactored#59]
The CastChecked for the AnimationInstance (AlsCharacter.cpp line 87) gives a hard crash during PostInitializeComponents so the anim instance can never be set up for a new inherited BP. I converted to regular cast and works to let me into the new BP to set it up. Maybe log an error letting the user know what is missing rather than the checks on init?

**Comment by Sixze** [comment]
Fixed in a0b8bc4a58587b01233b5fe3b2eb7921d4ffb4b4.
