### ISSUE TITLE
Issues that I've found.

### ISSUE THREAD

**Issue by LifeDreamer24** [Sixze/ALS-Refactored#60]
[ALS Refactored](https://github.com/Sixze/ALS-Refactored)
---
### Ragdoll Issues
- [x] #61
- [ ] Jumping, using ragdoll in less than a second after the jump and getting back to the normal state in mid air launches you futher and can lead to mantle on higher places than usually reachable ones. (This one is more of an enhancement, but it can perhaps fix a small advantage if used in an official game.)

### Collision Issues
- [x] If you go near an object doing a linear movement towards the character, the following object will teleport this one in a glitchy and unusual way by attempting to push.
Be sure to play with thoses bugs for a little while in order to find some details that might help fixing everything.

*Wishing you an amazing day from Canada,
-Simon 👍*

**Comment by Sixze** [comment]
An issue with the ragdoll is that it can incorrectly inherit its initial speed when the character jumps at unstable fps. I kinda fixed this issue [here](https://github.com/Sixze/ALS-Refactored/commit/dd258c9dec25cfc9cae701fa38cf458bc7bbe75d), but a correct fix will require a deep dive into the physics engine and modification of its sources, so let's hope that Epic will notice and fix this issue.
