### ISSUE TITLE
Strong jerk when landing (Comparing version BP vs C++)

### ISSUE THREAD

**Issue by RavenGames** [Sixze/ALS-Refactored#66]
Strong jerk when landing, for comparison I have included a video of how it looks in the ALSV4 BP version.

ALSV4 BP
https://streamable.com/qws7dm

ALS Refactored (main 20.03.2022)
https://streamable.com/v1hyxr

Can you make a soft landing like the BP version has ?

**Comment by Sixze** [comment]
Fixed in f6e859a76d6d9b71d62bcfbae9b956fc253c2cb0.
