### ISSUE TITLE
Control Rig doesn't work in standalone game

### ISSUE THREAD

**Issue by Sixze** [Sixze/ALS-Refactored#74]
https://drive.google.com/file/d/1ZIPREPrDc9jf3odu68QqhN-O_5Q8XI_7/view

**Comment by Sixze** [comment]
@davchezt

Are you using the latest version of the plugin, don't have any local changes and have foot IK enabled? Because from my tests, this problem only occurs when foot IK is disabled.

**Comment by davchezt** [comment]
> 

hi, i use master branch clone and don't have any local changes, on leg split video i added some logic on character BP to change mesh other are original git repo

**Comment by Sixze** [comment]
This probably has something to do with retargeting. Can you send me your mesh so I can test on it?

**Comment by davchezt** [comment]
> This probably has something to do with retargeting. Can you send me your mesh so I can test on it?

Hi, i have updated version to current git this is result video [Updated Git](https://github.com/Sixze/ALS-Refactored/issues/74#issuecomment-1095317555)

**Comment by davchezt** [comment]
i have finish uploading project contain mesh i used with BP modification to change mesh, for mesh i use sharing animation so iam not retargeting mesh to ALS skeleton here [here project](https://drive.google.com/file/d/1ClFXrvsjBUURibb7-WaHfZCydW5KzjfK/view?usp=sharing)

**Comment by Sixze** [comment]
Just checked your project and it looks like everything is fine, https://github.com/Sixze/ALS-Refactored/issues/75 also can't be reproduced.

**Comment by davchezt** [comment]
> Just checked your project and it looks like everything is fine, #75 also can't be reproduced.

@Sixze  to reproduce, sprint and jum tham aim and turn about 180 deg, like when we sprint to north jump aiming and turn to south

[Here Result with default overlay](https://drive.google.com/file/d/1eGKUSiQPxPLgzchVqVto8NS-oeC_jHD0/view?usp=sharing)

**Comment by davchezt** [comment]
and to reproduce Land foot on pelvis on editor launch as stand alone than keep sprinting and jump while sprinting on land in first seconds foot are colliding with pelvis and seem foot not on ground than back to normal
here video standalone preview in editor and without editor:

[Editor Standalone Game](https://drive.google.com/file/d/1E_lYYge3NnlKeYxHCH-PPoLTMmd1yzXw/view?usp=sharing)
[Standalone Game no Editor](https://drive.google.com/file/d/1sqFFW3rv3YS4txqm9KZbc2vekRhACS-C/view?usp=sharing)

**Comment by davchezt** [comment]
Hi, i have shiping preview [here](https://drive.google.com/file/d/1uRZ-0WN5qj4h7zoDZC2hrBTxYS4Gn9Ui/view?usp=sharing)
On land foot colliding with pelvis is no issue, on land turn 180deg not extreme as play on editor

**Comment by Sixze** [comment]
I was able to reproduce issue with 180 turn during landing, but not the foot IK issue. Open `CR_Als` and compile it, maybe it will help with IK issues.

**Comment by davchezt** [comment]
Hello @Sixze i recently making dedicated server to test client build and standalone without editor [this is video preview](https://drive.google.com/file/d/1ByJGk8w-xPJ5YsK6Igk8DS3wn9AzZgQS/view?usp=sharing), result from standalone without editor and build are difference on standalone roll end are no problem but on build roll end seems has snap on right foot, but overall are great and smooth

thank you for this awesome work

**Comment by davchezt** [comment]
> I was able to reproduce issue with 180 turn during landing, but not the foot IK issue. Open `CR_Als` and compile it, maybe it will help with IK issues.

Hello @Sixze this issue #72 on foot ik is not your issue or replication issue i think, this is causing by Controll Rig not initialize properly on Standalone, it only work with inside editor and package however i have test on build controll rig works on dedicated mode or normal mode, so this issue can be closed, thank you

**Comment by Sixze** [comment]
I'll leave this issue open until I find a solution, or until Epic fixes this bug in case it's an engine issue.

**Comment by davchezt** [comment]
i seen this issue not resolved yet https://issues.unrealengine.com/issue/UE-72326

**Comment by Sixze** [comment]
It seems that this issue only affects Unreal Engine 5.0, because on 4.26 everything is fine.

**Comment by Sixze** [comment]
I tested this issue on a separate from ALS project, but it still reproduced. Looks like this is an engine bug and we should wait for a fix from Epic Games.

**Comment by davchezt** [comment]
> I tested this issue on a separate from ALS project, but it still reproduced. Looks like this is an engine bug and we should wait for a fix from Epic Games.

ah i see, and yes i have tried with Third Person Template and IK also not working on standalone

**Comment by Sixze** [comment]
Looks like Epic fixed this issue in Unreal Engine 5.0.2. I am closing this issue.
