### ISSUE TITLE
Leg split on land when jump turn

### ISSUE THREAD

**Issue by davchezt** [Sixze/ALS-Refactored#75]
hello i have found another bug. this appear when rotation follow or aiming
[Leg Split (Video Preview)](https://drive.google.com/file/d/1hAPm2P74rcsZ_mw0upVhz1Z4s0n4D3CG/view?usp=sharing)

**Comment by Sixze** [comment]
I recently fixed this issue with landing, make sure you have the latest version of the plugin

**Comment by davchezt** [comment]
> I recently fixed this issue with landing, make sure you have the latest version of the plugin

ah nice, thank you for this awesome work

**Comment by davchezt** [comment]
hello i want to confirm this issue still remain on https://github.com/Sixze/ALS-Refactored/commit/b50c0d5734bdac2fcea6475f4581e5c5651c41b3

**Comment by Sixze** [comment]
Fixed in a8bdfc6c328cbd52ad489aea8f5d3d2827d5a6d9.
