### ISSUE TITLE
Mantle not sync on Client (Dedicated Server Mode)

### ISSUE THREAD

**Issue by Sixze** [Sixze/ALS-Refactored#76]
https://drive.google.com/file/d/1Xk_nWE79a-kSQeeq2AfOxkLaV2nFx0jD/view

**Comment by CanisHelix** [comment]
@Sixze Is this still an issue? It's the only issue listed here holding me back on moving over to ALS-Refactored from Community.

**Comment by Sixze** [comment]
Yes, but this issue is not critical at all and it should not prevent you from using the plugin

**Comment by Sixze** [comment]
I suspect this issue is that animation montage and root motion source are not synchronized with each other. They play independently, there is no guarantee that they will start at the same time for clients, and the character movement component can adjust the time of root motion sources so that it is synchronized on all clients, while regular animation montages do not have such a mechanism, so their playback time may not match.

The Gameplay Ability System has a built-in mechanism for synchronizing the playback of animation montages between clients, so it's possible that this problem will go away on its own after replacing locomotion actions with abilities, but I'm not 100% sure.

**Comment by Sixze** [comment]
I didn't get too deep into the details of how animation montage synchronization works in GAS, but it looks like the server is updating and replicating `RepAnimMontageInfo` to other clients every frame, not just once per animation start.

I will isolate the GAS related stuff into a separate module so that the `ALS` and `ALSCamera` modules will not know anything about the abilities and will be able to work on their own. Instead, `ALS` and `ALSCamera` will provide an API that GAS will use to control the character.

Essentially, GAS will not be enforced, and if you don't need it, you can simply ignore it, or even cut it out of the plugin. You will lose locomotion actions, but the rest of the plugin will still work fine.

**Comment by Sixze** [comment]
Also, as a fallback plan, there is Motion Warping that can be used instead of root motion sources, but I'm not sure if it will work in multiplayer or in situations like mantling onto a moving platform.

**Comment by nekwo** [comment]
just an idea not up to this yet.. still replicating my climbing system but wouldn't we use get server world time to syncronize it to local game time here in AlsCharacte_Actions.cpp. Just asking if you that yet?

> 

// TODO Magic. I can't explain why, but this code fixes animation and root motion source desynchronization.

		const auto MontageStartTime{
			Parameters.MantlingType == EAlsMantlingType::InAir && IsLocallyControlled()
				? StartTime - FMath::GetMappedRangeValueClamped(
					  FVector2f{MantlingSettings->ReferenceHeight}, {GetWorld()->GetDeltaSeconds(), 0.0f}, Parameters.MantlingHeight)
				: StartTime
		

 };

**Comment by Sixze** [comment]
> Just found [an idea](https://landelare.github.io/2022/05/15/climbing-with-root-motion.html) to simplify it

I implemented this algorithm, but left it optional because while it produces an accurate start time, it does not produce the best looking result. Perhaps I missed something while implementing it, idk.

**Comment by Sixze** [comment]
Fixed in 7a17cc0113790d27aa96bfce9bd77215555b6e99. It turns out that simply changing the animation montage time from the root motion source and disabling network smoothing is enough to solve this issue.

**Comment by watsonsong** [comment]
> Also, as a fallback plan, there is Motion Warping that can be used instead of root motion sources, but I'm not sure if it will work in multiplayer or in situations like mantling onto a moving platform.

I am looking for a way to implement other type of movement. Motion Warping seems a simply and good way instead of calculate by my self. I have not been dive into it. But is there any problem when use it in network? And maybe mantle could implement by this way?
