### ISSUE TITLE
Modifying Tick Bones messes with Master-Pose

### ISSUE THREAD

**Issue by mhomde** [Sixze/ALS-Refactored#77]
Hi, 

Since tick bones is changed in code it'll interfere with using Master-Pose (which needs "Always tick and refresh bones" to work"). Maybe add some secondary bool for that?

**Comment by Sixze** [comment]
Fixed 99ac009925b67be69cf6df09e0c31c2c0fa4ac79.

The plugin will now keep the default `VisibilityBasedAnimTickOption`, at least if another `VisibilityBasedAnimTickOption` is not required by the plugin to work properly.
