### ISSUE TITLE
Problem with feet when packaging on shipping.

### ISSUE THREAD

**Issue by blackhawk71** [Sixze/ALS-Refactored#79]
When packaging the project on shipping the control rig for the feet isn't working after mantle, the feet become stretched.

**Comment by Sixze** [comment]
I checked the packaged build and didn't find any issues. Can you please provide some details about the issue? A video or build of the game can help too.

**Comment by blackhawk71** [comment]
It seems that it has been resolved with UE5 5.0.1. I built it again and everything seems fine now
