### ISSUE TITLE
Two-handed pistol Overlay Mode is broken while Sprinting

### ISSUE THREAD

**Issue by Solessfir** [Sixze/ALS-Refactored#82]
![HighresScreenshot00000](https://user-images.githubusercontent.com/34831419/168049792-d11e1ccf-d86f-4e12-9f02-e85fdd2e70cb.png)

**Comment by Sixze** [comment]
Yes, there is such an issue. I fixed it, but the commit with the changes will be a little later.

**Comment by Sixze** [comment]
Fixed in 512d0bc5da02f55b557505703a4069cc6054e102.
